version: "3.8"

services:

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
    command:
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend:
    build:
      context: backend
      dockerfile: optimised.dockerfile
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - db:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=tome
    env_file: .env

  frontend:
    build:
      context: frontend
      dockerfile: prod.dockerfile
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.middlewares.spa-rewrite.replacepath.path=/"

volumes:
  db:
