<template>
  <div>
    <v-alert
      type="error"
      v-for="(error, i) in $store.state.twoFactor.errors"
      :key="i"
      dismissible
      @input="$event || $store.commit('twoFactor/delError', i)"
    >{{ error }}</v-alert>
    <h1>Two-factor authentication</h1>
    <p>
      Help to secure your account by adding a second step when you login to verify it's
      really you.
    </p>
    <template v-if="status === 'setup_complete'">
      <p>Two-factor authentication is currently enabled.</p>
      <v-btn @click="disable" outlined color="error">Disable</v-btn>
      <h2 class="mt-4">Recovery</h2>
      <p>
        If you ever lose your two-factor authentication device, you can use this recovery
        code to regain access to your account:
      </p>
      <p><code>{{ recovery }}</code></p>
      <p>Make sure to store it in a safe place!</p>
      <p>
        If your recovery code is compromised, you should immediately regenerate it to
        prevent account take-over.
      </p>
      <v-btn @click="regenerateRecovery" color="error" outlined>Regenerate</v-btn>
    </template>
    <div v-else-if="status === 'setup_in_progress'">
      <template v-if="secret">
        <p>
          To set up, first scan this QR code into your authenticator app:
        </p>
        <img :src="qrCodeURL" :alt="secret" class="mx-auto d-block mb-4">
        <p>
          Alternatively, you can manually enter the secret key:
          <code class="ms-2">{{ secret }}</code>
        </p>
      </template>
      <p>
        <span v-if="!secret">Two-factor authentication setup is in progress.</span>
        To complete setup, enter a code generated by your authenticator app.
      </p>
      <v-form @submit.prevent="confirmSetup" autocomplete="off" class="mx-n2">
        <v-text-field
          type="tel"
          outlined
          placeholder="123456"
          v-model="code"
          class="mx-2"
        ></v-text-field>
        <div class="px-2 mx-n2 mb-n4">
          <v-btn type="submit" outlined color="info" class="mx-2 mb-4">Confirm</v-btn>
          <v-btn outlined color="error" @click="cancelSetup" class="mx-2 mb-4">Cancel Setup</v-btn>
        </div>
      </v-form>
    </div>
    <template v-else-if="status === 'disabled'">
      <p>
        Click below to set up two-factor authentication on your account. You'll need to
        install a TOTP-compatible app on a mobile device, such as Google Authenticator
        or Duo.
      </p>
      <v-btn @click="beginSetup" outlined color="info">Set up</v-btn>
    </template>
  </div>
</template>

<script>
import Store from '@/store'
import { mapActions } from 'vuex'

export default {
  name: 'TwoFactor',
  computed: {
    status () {
      return this.$store.state.twoFactor.status
    },
    secret () {
      return this.$store.state.twoFactor.secret
    },
    code: {
      get () {
        return this.$store.state.twoFactor.code
      },
      set (value) {
        this.$store.state.twoFactor.code = value
      }
    },
    qrCodeURL () {
      return this.$store.state.twoFactor.qrCodeURL
    },
    recovery () {
      return this.$store.state.twoFactor.recovery
    },
    finished: {
      get () {
        return this.$store.state.twoFactor.finished
      },
      set (value) {
        this.$store.state.twoFactor.finished = value
      }
    }
  },
  methods: {
    ...mapActions('twoFactor', [
      'beginSetup',
      'cancelSetup',
      'confirmSetup',
      'disable',
      'regenerateRecovery'
    ])
  },
  beforeRouteEnter (whither, whence, next) {
    Store.dispatch('twoFactor/init').then(next)
  }
}
</script>

<style lang="scss"></style>
